name: CI Pipeline

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Instalar dependências
        run: npm install

      - name: Rodar lint
        run: npx eslint . || true

      - name: Build Docker
        run: docker build -t iscoolgpt .